#sh	install_GxCreamMachine.sh
sh	install_abgate.sh
#sh	install_alo_looper.sh
sh	install_bollie.sh
#sh	install_cabsim.sh
#sh	install_convoLV2.sh
#sh	install_distrho.sh
#sh	install_gx_plugins.sh
#sh	install_gxblueamp.sh
#sh	install_gxdenoiser.sh
sh	install_gxplexi.sh
#sh	install_invada.sh
#sh	install_irlv2.sh
#sh	install_jackPiledmeter.sh
#sh	install_midding.sh
#sh	install_mod-meter.sh
#sh	install_mod-pitchshifter.sh
sh	install_rkrlv2.sh
#sh	install_screcord.sh
#sh	install_shiro.sh
sh	install_tap.sh
#sh	install_x42_eq.sh
sh	install_x42tuna.sh
sh  install_x42TinyAmp.sh
#sh	install_zamaudio.sh
sh  zynthian-modgui.sh
sh  update_mod_gui.sh
